2021-04-18 13:56:04,306 INFO    MainThread:1438 [wandb_setup.py:_flush():69] setting env: {}
2021-04-18 13:56:04,306 INFO    MainThread:1438 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-18 13:56:04,307 INFO    MainThread:1438 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '929e86241d1f7b8ce4c06f6eb68602d06923de0d'}
2021-04-18 13:56:04,307 INFO    MainThread:1438 [wandb_init.py:_log_setup():336] Logging user logs to /Users/shilpakancharla/Documents/metoo-classification/wandb/run-20210418_135604-s61f6r1m/logs/debug.log
2021-04-18 13:56:04,308 INFO    MainThread:1438 [wandb_init.py:_log_setup():337] Logging internal logs to /Users/shilpakancharla/Documents/metoo-classification/wandb/run-20210418_135604-s61f6r1m/logs/debug-internal.log
2021-04-18 13:56:04,309 INFO    MainThread:1438 [wandb_init.py:init():369] calling init triggers
2021-04-18 13:56:04,310 INFO    MainThread:1438 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-18 13:56:04,311 INFO    MainThread:1438 [wandb_init.py:init():389] re-initializing run, found existing run on stack: wqe3stue
2021-04-18 13:56:04,315 INFO    MainThread:1438 [wandb_run.py:finish():1167] finishing run shilpakancharla/metoo-classification/wqe3stue
2021-04-18 13:56:04,317 INFO    MainThread:1438 [jupyter.py:save_history():320] not saving jupyter history
2021-04-18 13:56:04,317 INFO    MainThread:1438 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-04-18 13:56:04,317 INFO    MainThread:1438 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-04-18 13:56:04,317 INFO    MainThread:1438 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-04-18 13:56:04,319 INFO    MainThread:1438 [wandb_run.py:_restore():1466] restore
2021-04-18 13:56:04,477 INFO    MainThread:1438 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 860
  total_bytes: 860
}

2021-04-18 13:56:04,859 INFO    MainThread:1438 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 860
  total_bytes: 3405
}

2021-04-18 13:56:05,016 INFO    MainThread:1438 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 860
  total_bytes: 3405
}

2021-04-18 13:56:05,123 INFO    MainThread:1438 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 860
  total_bytes: 3405
}

2021-04-18 13:56:05,226 INFO    MainThread:1438 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3405
  total_bytes: 3405
}

2021-04-18 13:56:05,334 INFO    MainThread:1438 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3405
  total_bytes: 3405
}

2021-04-18 13:56:05,442 INFO    MainThread:1438 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3405
  total_bytes: 3405
}

2021-04-18 13:56:05,548 INFO    MainThread:1438 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3405
  total_bytes: 3405
}

2021-04-18 13:56:05,656 INFO    MainThread:1438 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3405
  total_bytes: 3405
}

2021-04-18 13:56:06,960 INFO    MainThread:1438 [wandb_run.py:_show_files():1838] logging synced files
2021-04-18 13:56:06,979 INFO    MainThread:1438 [wandb_init.py:init():418] starting backend
2021-04-18 13:56:06,979 INFO    MainThread:1438 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2021-04-18 13:56:06,987 INFO    MainThread:1438 [backend.py:ensure_launched():123] starting backend process...
2021-04-18 13:56:07,015 INFO    MainThread:1438 [backend.py:ensure_launched():127] started backend process with pid: 1829
2021-04-18 13:56:07,026 INFO    MainThread:1438 [wandb_init.py:init():423] backend started and connected
2021-04-18 13:56:07,034 INFO    MainThread:1438 [wandb_init.py:init():465] updated telemetry
2021-04-18 13:56:07,035 INFO    MainThread:1438 [wandb_init.py:init():484] communicating current version
2021-04-18 13:56:08,756 INFO    MainThread:1438 [wandb_init.py:init():489] got version response 
2021-04-18 13:56:08,756 INFO    MainThread:1438 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-18 13:56:08,951 INFO    MainThread:1438 [wandb_init.py:init():522] starting run threads in backend
2021-04-18 13:56:11,715 INFO    MainThread:1438 [wandb_run.py:_console_start():1524] atexit reg
2021-04-18 13:56:11,717 INFO    MainThread:1438 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-04-18 13:56:11,717 INFO    MainThread:1438 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-04-18 13:56:11,717 INFO    MainThread:1438 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-18 13:56:11,718 INFO    MainThread:1438 [wandb_init.py:init():546] run started, returning control to user process
2021-04-18 13:56:11,718 INFO    MainThread:1438 [wandb_config.py:__setitem__():141] config set vocab_size = 1000 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x128351490>>
2021-04-18 13:56:11,718 INFO    MainThread:1438 [wandb_run.py:_config_callback():749] config_cb vocab_size 1000 None
2021-04-18 13:56:11,719 INFO    MainThread:1438 [wandb_config.py:__setitem__():141] config set maxlen = 1000 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x128351490>>
2021-04-18 13:56:11,719 INFO    MainThread:1438 [wandb_run.py:_config_callback():749] config_cb maxlen 1000 None
2021-04-18 13:56:11,719 INFO    MainThread:1438 [wandb_config.py:__setitem__():141] config set batch_size = 32 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x128351490>>
2021-04-18 13:56:11,720 INFO    MainThread:1438 [wandb_run.py:_config_callback():749] config_cb batch_size 32 None
2021-04-18 13:56:11,720 INFO    MainThread:1438 [wandb_config.py:__setitem__():141] config set embedding_dims = 10 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x128351490>>
2021-04-18 13:56:11,720 INFO    MainThread:1438 [wandb_run.py:_config_callback():749] config_cb embedding_dims 10 None
2021-04-18 13:56:11,720 INFO    MainThread:1438 [wandb_config.py:__setitem__():141] config set filters = 16 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x128351490>>
2021-04-18 13:56:11,721 INFO    MainThread:1438 [wandb_run.py:_config_callback():749] config_cb filters 16 None
2021-04-18 13:56:11,721 INFO    MainThread:1438 [wandb_config.py:__setitem__():141] config set kernel_size = 3 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x128351490>>
2021-04-18 13:56:11,721 INFO    MainThread:1438 [wandb_run.py:_config_callback():749] config_cb kernel_size 3 None
2021-04-18 13:56:11,722 INFO    MainThread:1438 [wandb_config.py:__setitem__():141] config set hidden_dims = 250 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x128351490>>
2021-04-18 13:56:11,722 INFO    MainThread:1438 [wandb_run.py:_config_callback():749] config_cb hidden_dims 250 None
2021-04-18 13:56:11,722 INFO    MainThread:1438 [wandb_config.py:__setitem__():141] config set epochs = 10 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x128351490>>
2021-04-18 13:56:11,723 INFO    MainThread:1438 [wandb_run.py:_config_callback():749] config_cb epochs 10 None
